= Assisted-Board-Games
:gitHubUserName: oliviercailloux
:groupId: io.github.{gitHubUserName}
:artifactId: assisted-board-games
:repository: Assisted-Board-Games

image:https://travis-ci.com/{gitHubUserName}/{repository}.svg?branch=master["Build Status", link="https://travis-ci.com/{gitHubUserName}/{repository}"]

A Java project developed by students during the https://github.com/oliviercailloux/java-course[Java course] taught at Université Paris-Dauphine (in http://www.mido.dauphine.fr/[MIDO] L3 and M2 MIAGE).

The code is hereby published under the MIT License, with their permission.

Project maintained by :
Dahuiss AMOUSSOU, Marina ATANGANA, James BURTON, Aaron DEMAY, Yasmine HAMNACHE, Kerim HUDAYBERDIYEV, Anam SHAIKH YUNUS+
L3 MIAGE in Apprenticeship

=== *Project description*
In this project, the concept of the Assited Board will be implemented. The latter represents a game board as well as an interactive tablet for each player. 

For this project, we will make maximum use of existing libraries and good practices.
Development in iterations.

=== *Description for iteration #2 - Project leader: James BURTON*

- *PR#1: Aaron DEMAY & Dahuiss AMOUSSOU* +
 +
+++<u>Task: Creation of Clock Class</u>+++ +
Create a diagram for manging the clock will be useful for both chess and checkers, the aim is to measure how long a game takes from start to finish and also to add a time constraint. +
 +
First, a player sets a time limit that he must respect (10 minutes for each player, for example), with idleness included. +
 +
Then, if a player gets disconnected from the game, he has 1 min to reconnect or he will automatically lose the game. +
 +
This tries to solve the problems of long games and player idleness (this prevents an opponent from waiting too long). +
 +
We will be using two types of diagrams, a class diagram and sequence diagram. +
 +

- *PR#2: Anam SHAIKH YUNUS & Yasmine HAMNACHE* +
+
+++<u>Task: Improvement of generalization</u>+++ +
Goals: +
1. Have 2 interfaces: *Move* and *Board* with implementations for both (for chess and checkers) +
2. Replace list with multiplicity +
3. To first focus on improving the chess game (for the next iteration), and later on see the checkers game +
 +
This task solves the following problem: our application will be able to manage multiple types of games (at least two, chess and checkers). Because these game are different, each needs specific classes. +
*[TYPE OF DIAGRAM?]* +
 +

- *PR#3: Kerim HUDAYBERDIYEV & Marina ATANGANA* +
+
+++<u>Task: Possible moves during a game of checkers and chess</u>+++ +
*[POSSIBLE MOVES OR MOVES MADE DURING THE GAME??]* +
Goal: Create a class containing all possible moves +
+
What we will do: +
1. Create a parent class diagram containing all moves that are common to both chess and checkers +
2. Create a child class containing all possible moves for a checkers game +
3. Create a child class containing all possible moves for a chess game +
